import{q,one,num,money}from'./lib.js';
export async function productList(db,storeId){return(await q(db,'SELECT * FROM products WHERE store_id=? AND active=1 ORDER BY category,name',storeId)).results||[]}
export async function customerList(db,storeId){return(await q(db,`SELECT c.*,COALESCE(SUM(d.balance),0) debt_balance FROM customers c LEFT JOIN customer_debts d ON d.customer_id=c.id WHERE c.store_id=? AND c.active=1 GROUP BY c.id ORDER BY c.name COLLATE NOCASE`,storeId)).results||[]}
export async function debtList(db,storeId){return(await q(db,`SELECT d.*,c.name customer_name FROM customer_debts d JOIN customers c ON c.id=d.customer_id WHERE d.store_id=? ORDER BY d.created_at DESC LIMIT 500`,storeId)).results||[]}
export async function cashList(db,storeId){return(await q(db,'SELECT * FROM cash_entries WHERE store_id=? ORDER BY created_at DESC LIMIT 300',storeId)).results||[]}
export async function saleList(db,storeId){return(await q(db,'SELECT * FROM sales WHERE store_id=? ORDER BY created_at DESC LIMIT 200',storeId)).results||[]}
export async function dashboard(db,storeId){const today=new Date().toISOString().slice(0,10);const s=await one(db,`SELECT COUNT(*) orders,COALESCE(SUM(total),0) revenue,COALESCE(SUM(profit),0) profit FROM sales WHERE store_id=? AND status='completed' AND substr(created_at,1,10)=?`,storeId,today);const d=await one(db,'SELECT COALESCE(SUM(balance),0) balance FROM customer_debts WHERE store_id=?',storeId);const st=await one(db,'SELECT COALESCE(SUM(stock*cost_price),0) value,SUM(CASE WHEN active=1 AND track_stock=1 AND stock<=min_stock THEN 1 ELSE 0 END) low FROM products WHERE store_id=?',storeId);const c=await one(db,`SELECT COALESCE(SUM(CASE WHEN entry_type='income' THEN amount ELSE -amount END),0) net FROM cash_entries WHERE store_id=? AND substr(created_at,1,10)=?`,storeId,today);const recent=(await q(db,'SELECT id,total,customer_name,created_at FROM sales WHERE store_id=? ORDER BY created_at DESC LIMIT 8',storeId)).results||[];return{date:today,orders:num(s?.orders),revenue:money(s?.revenue),profit:Math.round(num(s?.profit)),debtBalance:money(d?.balance),inventoryValue:money(st?.value),lowStock:num(st?.low),cashNet:Math.round(num(c?.net)),recentSales:recent}}
export async function report(db,storeId,from='0000-01-01',to='9999-12-31'){const s=await one(db,`SELECT COUNT(*) orders,COALESCE(SUM(total),0) revenue,COALESCE(SUM(cost_total),0) cost,COALESCE(SUM(profit),0) profit FROM sales WHERE store_id=? AND status='completed' AND substr(created_at,1,10) BETWEEN ? AND ?`,storeId,from,to);const c=await one(db,`SELECT COALESCE(SUM(CASE WHEN entry_type='income' THEN amount ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN entry_type='expense' THEN amount ELSE 0 END),0) expense FROM cash_entries WHERE store_id=? AND substr(created_at,1,10) BETWEEN ? AND ?`,storeId,from,to);const byDay=(await q(db,`SELECT substr(created_at,1,10) day,COUNT(*) orders,SUM(total) revenue,SUM(profit) profit FROM sales WHERE store_id=? AND status='completed' AND substr(created_at,1,10) BETWEEN ? AND ? GROUP BY day ORDER BY day`,storeId,from,to)).results||[];return{orders:num(s?.orders),revenue:money(s?.revenue),cost:money(s?.cost),profit:Math.round(num(s?.profit)),income:money(c?.income),expense:money(c?.expense),byDay}}
export async function snapshot(db,storeId){const[store,products,customers,debts,cash,sales,dash]=await Promise.all([one(db,'SELECT * FROM stores WHERE id=?',storeId),productList(db,storeId),customerList(db,storeId),debtList(db,storeId),cashList(db,storeId),saleList(db,storeId),dashboard(db,storeId)]);return{store,products,customers,debts,cash,sales,dashboard:dash}}
